
import type { Product, Order } from './types';

export const categories = [
  { id: 1, name: 'All' },
  { id: 2, name: 'T-shirts' },
  { id: 3, name: 'Shirts' },
  { id: 4, name: 'Pants' },
  { id: 5, name: 'Shorts' },
];

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Classic Cotton T-Shirt',
    price: 25.00,
    category: 'T-shirts',
    color: 'White',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'A timeless classic, this 100% cotton t-shirt is a wardrobe essential. Soft, breathable, and durable.',
    aiHint: "white t-shirt",
  },
  {
    id: 'prod_002',
    name: 'Slim-Fit Denim Pants',
    price: 75.00,
    category: 'Pants',
    color: 'Blue',
    sizes: ['30x30', '32x30', '32x32', '34x32'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Modern slim-fit jeans crafted from premium stretch denim for maximum comfort and style.',
    aiHint: "denim jeans",
  },
  {
    id: 'prod_003',
    name: 'Floral Sundress',
    price: 60.00,
    category: 'Shirts',
    color: 'Yellow',
    sizes: ['XS', 'S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Light and airy, this floral sundress is perfect for warm days. Features a flattering A-line cut.',
    aiHint: "floral dress",
  },
  {
    id: 'prod_004',
    name: 'Leather Biker Jacket',
    price: 250.00,
    category: 'Shirts',
    color: 'Black',
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'A statement piece, this genuine leather jacket adds an edge to any outfit.',
    aiHint: "leather jacket",
  },
  {
    id: 'prod_005',
    name: 'Kids Graphic Hoodie',
    price: 40.00,
    category: 'T-shirts',
    color: 'Gray',
    sizes: ['2T', '3T', '4T', '5T'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Keep them cozy in this fun graphic hoodie, made from a soft cotton blend.',
    aiHint: "kids hoodie",
  },
  {
    id: 'prod_006',
    name: 'Formal Wool Blazer',
    price: 180.00,
    category: 'Shirts',
    color: 'Charcoal',
    sizes: ['38R', '40R', '42R', '44L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Sharpen up your look with this expertly tailored wool blazer.',
    aiHint: "wool blazer",
  },
  {
    id: 'prod_007',
    name: 'Silk Evening Gown',
    price: 350.00,
    category: 'Shirts',
    color: 'Red',
    sizes: ['2', '4', '6', '8', '10'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Make an entrance with this stunning red silk evening gown, featuring an elegant drape.',
    aiHint: "evening gown",
  },
  {
    id: 'prod_008',
    name: 'Kids Rainbow T-Shirt',
    price: 20.00,
    category: 'T-shirts',
    color: 'Multi',
    sizes: ['2T', '3T', '4T', '5T'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
    ],
    description: 'A bright and cheerful t-shirt with a vibrant rainbow print.',
    aiHint: "rainbow shirt",
  },
  {
    id: 'prod_009',
    name: 'Linen Trousers',
    price: 65.00,
    category: 'Pants',
    color: 'Beige',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Stay cool and comfortable in these lightweight linen trousers.',
    aiHint: "linen trousers",
  },
  {
    id: 'prod_010',
    name: 'High-Waisted Leggings',
    price: 50.00,
    category: 'Pants',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
    ],
    description: 'Versatile and comfortable, these high-waisted leggings are perfect for workouts or casual wear.',
    aiHint: "black leggings",
  },
  {
    id: 'prod_011',
    name: 'Denim Shorts',
    price: 45.00,
    category: 'Shorts',
    color: 'Blue',
    sizes: ['XS', 'S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Classic denim shorts, a summer wardrobe staple.',
    aiHint: "denim shorts",
  },
  {
    id: 'prod_012',
    name: 'Cashmere Sweater',
    price: 220.00,
    category: 'Shirts',
    color: 'Navy',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    description: 'Luxuriously soft 100% cashmere sweater for ultimate warmth and sophistication.',
    aiHint: "cashmere sweater",
  },
];

export const productFilters = {
  colors: ['White', 'Blue', 'Yellow', 'Black', 'Gray', 'Charcoal', 'Red', 'Multi', 'Beige', 'Navy'],
  priceRange: { min: 20, max: 350 },
};
