export const categories = [
  { id: 1, name: 'Men' },
  { id: 2, name: 'Women' },
  { id: 3, name: 'Kids' },
  { id: 4, name: 'Sale' },
  { id: 5, name: 'New Arrivals' },
];

export const products = [
  {
    id: 'prod_001',
    name: 'Classic Cotton T-Shirt',
    price: 25.00,
    category: 'Men',
    color: 'White',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.5,
    reviews: 120,
    description: 'A timeless classic, this 100% cotton t-shirt is a wardrobe essential. Soft, breathable, and durable.',
    aiHint: "white t-shirt",
  },
  {
    id: 'prod_002',
    name: 'Slim-Fit Denim Jeans',
    price: 75.00,
    category: 'Men',
    color: 'Blue',
    sizes: ['30x30', '32x30', '32x32', '34x32'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.7,
    reviews: 95,
    description: 'Modern slim-fit jeans crafted from premium stretch denim for maximum comfort and style.',
    aiHint: "denim jeans",
  },
  {
    id: 'prod_003',
    name: 'Floral Sundress',
    price: 60.00,
    category: 'Women',
    color: 'Yellow',
    sizes: ['XS', 'S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.8,
    reviews: 210,
    description: 'Light and airy, this floral sundress is perfect for warm days. Features a flattering A-line cut.',
    aiHint: "floral dress",
  },
  {
    id: 'prod_004',
    name: 'Leather Biker Jacket',
    price: 250.00,
    category: 'Women',
    color: 'Black',
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.9,
    reviews: 150,
    description: 'A statement piece, this genuine leather jacket adds an edge to any outfit.',
    aiHint: "leather jacket",
  },
  {
    id: 'prod_005',
    name: 'Kids Graphic Hoodie',
    price: 40.00,
    category: 'Kids',
    color: 'Gray',
    sizes: ['2T', '3T', '4T', '5T'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.6,
    reviews: 80,
    description: 'Keep them cozy in this fun graphic hoodie, made from a soft cotton blend.',
    aiHint: "kids hoodie",
  },
  {
    id: 'prod_006',
    name: 'Formal Wool Blazer',
    price: 180.00,
    category: 'Men',
    color: 'Charcoal',
    sizes: ['38R', '40R', '42R', '44L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.7,
    reviews: 65,
    description: 'Sharpen up your look with this expertly tailored wool blazer.',
    aiHint: "wool blazer",
  },
  {
    id: 'prod_007',
    name: 'Silk Evening Gown',
    price: 350.00,
    category: 'Women',
    color: 'Red',
    sizes: ['2', '4', '6', '8', '10'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.9,
    reviews: 78,
    description: 'Make an entrance with this stunning red silk evening gown, featuring an elegant drape.',
    aiHint: "evening gown",
  },
  {
    id: 'prod_008',
    name: 'Kids Rainbow T-Shirt',
    price: 20.00,
    category: 'Kids',
    color: 'Multi',
    sizes: ['2T', '3T', '4T', '5T'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
    ],
    rating: 4.5,
    reviews: 110,
    description: 'A bright and cheerful t-shirt with a vibrant rainbow print.',
    aiHint: "rainbow shirt",
  },
  {
    id: 'prod_009',
    name: 'Linen Trousers',
    price: 65.00,
    category: 'Men',
    color: 'Beige',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.4,
    reviews: 88,
    description: 'Stay cool and comfortable in these lightweight linen trousers.',
    aiHint: "linen trousers",
  },
  {
    id: 'prod_010',
    name: 'High-Waisted Leggings',
    price: 50.00,
    category: 'Women',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
    ],
    rating: 4.8,
    reviews: 300,
    description: 'Versatile and comfortable, these high-waisted leggings are perfect for workouts or casual wear.',
    aiHint: "black leggings",
  },
  {
    id: 'prod_011',
    name: 'Waterproof Raincoat',
    price: 90.00,
    category: 'Kids',
    color: 'Yellow',
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.7,
    reviews: 92,
    description: 'A bright yellow raincoat to keep your little one dry on rainy days.',
    aiHint: "yellow raincoat",
  },
  {
    id: 'prod_012',
    name: 'Cashmere Sweater',
    price: 220.00,
    category: 'Men',
    color: 'Navy',
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://placehold.co/400x400.png',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    rating: 4.9,
    reviews: 130,
    description: 'Luxuriously soft 100% cashmere sweater for ultimate warmth and sophistication.',
    aiHint: "cashmere sweater",
  },
];

export const cartItems = [
  { ...products[0], quantity: 1 },
  { ...products[2], quantity: 2 },
  { ...products[4], quantity: 1 },
];

export const userAddresses = [
  {
    id: 'addr_1',
    name: 'John Doe',
    addressLine1: '123 Market St',
    addressLine2: 'Apt 4B',
    city: 'Metropolis',
    state: 'NY',
    zip: '10001',
    country: 'USA',
    isDefault: true,
  },
  {
    id: 'addr_2',
    name: 'John Doe',
    addressLine1: '456 Innovation Dr',
    addressLine2: '',
    city: 'Techville',
    state: 'CA',
    zip: '94043',
    country: 'USA',
    isDefault: false,
  },
];

export const pastOrders = [
  {
    id: 'ORD-2023-001',
    date: '2023-10-15',
    status: 'Delivered',
    total: 105.00,
    items: [
      { ...products[1], quantity: 1 },
      { ...products[0], quantity: 1 },
    ],
    shippingAddress: userAddresses[0]
  },
  {
    id: 'ORD-2023-002',
    date: '2023-11-01',
    status: 'Delivered',
    total: 290.00,
    items: [
      { ...products[3], quantity: 1 },
      { ...products[4], quantity: 1 },
    ],
    shippingAddress: userAddresses[0]
  },
    {
    id: 'ORD-2024-003',
    date: '2024-01-20',
    status: 'Processing',
    total: 415.00,
    items: [
      { ...products[6], quantity: 1 },
      { ...products[8], quantity: 1 },
    ],
    shippingAddress: userAddresses[1]
  }
];

export const productFilters = {
  colors: ['White', 'Blue', 'Yellow', 'Black', 'Gray', 'Charcoal', 'Red', 'Multi', 'Beige', 'Navy'],
  priceRange: { min: 20, max: 350 },
};
